import { MediaItem } from '../types';
import { analyzeMediaForChromecast } from './chromecastSpecs';

export const INITIAL_SAMPLE_MEDIA: Partial<MediaItem>[] = [
  {
    id: 'sample-1',
    fileName: 'Dune.Part.Two.2024.1080p.10bit.H264.DTS-HD.MA.7.1.mkv',
    filePath: '/media/movies/Dune.Part.Two.2024.1080p.10bit.H264.DTS-HD.MA.7.1.mkv',
    directory: '/media/movies',
    title: 'Dune: Part Two (2024)',
    mediaType: 'movie',
    fileSizeBytes: 18450000000, // ~18.4 GB
    durationSeconds: 9960,
    container: 'mkv',
    addedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastScannedAt: new Date().toISOString(),
    streams: [
      {
        index: 0,
        type: 'video',
        codec: 'h264',
        codecLong: 'H.264 / AVC / MPEG-4 AVC',
        profile: 'High 10',
        pixelFormat: 'yuv420p10le',
        bitDepth: 10,
        width: 1920,
        height: 1080,
        fps: 23.976,
      },
      {
        index: 1,
        type: 'audio',
        codec: 'dts',
        codecLong: 'DTS-HD Master Audio 7.1',
        channels: 8,
        channelLayout: '7.1',
        sampleRate: 48000,
        language: 'eng',
        title: 'English DTS-HD MA 7.1 Surround',
      },
      {
        index: 2,
        type: 'audio',
        codec: 'ac3',
        codecLong: 'Dolby Digital 5.1',
        channels: 6,
        channelLayout: '5.1',
        sampleRate: 48000,
        language: 'spa',
        title: 'Spanish AC-3 5.1',
      },
      {
        index: 3,
        type: 'subtitle',
        codec: 'pgs',
        codecLong: 'HDMV PGS Subtitle (Bitmap)',
        language: 'eng',
        title: 'English (PGS)',
      },
      {
        index: 4,
        type: 'subtitle',
        codec: 'subrip',
        codecLong: 'SubRip Text (SRT)',
        language: 'fre',
        title: 'French Subtitles',
      },
    ],
  },
  {
    id: 'sample-2',
    fileName: 'Severance.S01E01.2160p.UHD.HEVC.EAC3.Atmos.mkv',
    filePath: '/media/tv/Severance/Season 01/Severance.S01E01.2160p.UHD.HEVC.EAC3.Atmos.mkv',
    directory: '/media/tv/Severance',
    title: 'Severance - S01E01 "Good News About Hell"',
    mediaType: 'tv',
    season: 1,
    episode: 1,
    fileSizeBytes: 4820000000, // ~4.8 GB
    durationSeconds: 3420,
    container: 'mkv',
    addedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    lastScannedAt: new Date().toISOString(),
    streams: [
      {
        index: 0,
        type: 'video',
        codec: 'hevc',
        codecLong: 'H.265 / HEVC Main 10',
        profile: 'Main 10',
        pixelFormat: 'yuv420p10le',
        bitDepth: 10,
        width: 3840,
        height: 2160,
        fps: 24,
      },
      {
        index: 1,
        type: 'audio',
        codec: 'eac3',
        codecLong: 'Dolby Digital Plus with Atmos',
        channels: 6,
        channelLayout: '5.1(side)',
        sampleRate: 48000,
        language: 'eng',
      },
      {
        index: 2,
        type: 'subtitle',
        codec: 'subrip',
        codecLong: 'SubRip Text (SRT)',
        language: 'eng',
        title: 'English SDH',
      },
    ],
  },
  {
    id: 'sample-3',
    fileName: 'Oppenheimer.2023.2160p.IMAX.TrueHD.7.1.Atmos.VC1.m2ts',
    filePath: '/media/movies/Oppenheimer.2023.2160p.IMAX.TrueHD.7.1.Atmos.VC1.m2ts',
    directory: '/media/movies',
    title: 'Oppenheimer (2023)',
    mediaType: 'movie',
    fileSizeBytes: 62000000000, // ~62 GB
    durationSeconds: 10800,
    container: 'm2ts',
    addedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    lastScannedAt: new Date().toISOString(),
    streams: [
      {
        index: 0,
        type: 'video',
        codec: 'vc1',
        codecLong: 'SMPTE VC-1 Advanced Profile',
        profile: 'Advanced',
        pixelFormat: 'yuv420p',
        bitDepth: 8,
        width: 3840,
        height: 2160,
        fps: 23.976,
      },
      {
        index: 1,
        type: 'audio',
        codec: 'truehd',
        codecLong: 'Dolby TrueHD Audio',
        channels: 8,
        channelLayout: '7.1',
        sampleRate: 48000,
        language: 'eng',
      },
      {
        index: 2,
        type: 'subtitle',
        codec: 'ass',
        codecLong: 'Advanced SubStation Alpha',
        language: 'eng',
        title: 'Full Styling ASS',
      },
    ],
  },
  {
    id: 'sample-4',
    fileName: 'The.Bear.S02E06.Fishes.1080p.WEB-DL.H264.AAC.mp4',
    filePath: '/media/tv/The.Bear/Season 02/The.Bear.S02E06.Fishes.1080p.WEB-DL.H264.AAC.mp4',
    directory: '/media/tv/The.Bear',
    title: 'The Bear - S02E06 "Fishes"',
    mediaType: 'tv',
    season: 2,
    episode: 6,
    fileSizeBytes: 1850000000, // ~1.85 GB
    durationSeconds: 3960,
    container: 'mp4',
    addedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    lastScannedAt: new Date().toISOString(),
    streams: [
      {
        index: 0,
        type: 'video',
        codec: 'h264',
        codecLong: 'H.264 / AVC High Profile',
        profile: 'High',
        pixelFormat: 'yuv420p',
        bitDepth: 8,
        width: 1920,
        height: 1080,
        fps: 23.976,
      },
      {
        index: 1,
        type: 'audio',
        codec: 'aac',
        codecLong: 'Advanced Audio Coding (AAC-LC)',
        channels: 2,
        channelLayout: 'stereo',
        sampleRate: 48000,
        language: 'eng',
      },
    ],
  },
];

export function getProcessedInitialMedia(): MediaItem[] {
  return INITIAL_SAMPLE_MEDIA.map((item) => {
    const analysis = analyzeMediaForChromecast(item);
    return {
      ...(item as MediaItem),
      needsTranscode: analysis.needsTranscode,
      transcodeReasons: analysis.reasons,
      recommendation: analysis.recommendation,
    };
  });
}
